server:
  port: 8443
  compression:
    enabled: false
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:ssl.p12
    key-store-password: Raven123qweasd+
    key-store-type: PKCS12
    key-alias: ssl
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: false
    register-shutdown-hook: true
  application:
    name: valid_movies-api
  profiles:
    active: ${VALID_MOVIES_ENVIRONMENT:dev}
  datasource:
    url: ${VALID_MOVIES_DATASOURCE_URL:jdbc:mysql://localhost:3308/valid-movie-rental?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${VALID_MOVIES_DATASOURCE_USERNAME:root}
    password: ${VALID_MOVIES_DATASOURCE_PASSWORD:v4l1d-gu1d0-m4nt*}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    platform: mysql
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
    hibernate:
      naming:
        physical-strategy: valid.movies.api.hibernate.naming.LowerCasePhysicalNamingStrategy

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmry59I01VicxrlO76Ma6
          FLZ8JF5gjhP8xiJcdTsmUZjn/SHoiccjygILPbEfIqOqSjixxl0L8Vl6zbffMMoq
          UBgpFoiATbX/0Y6P2mVwZumIl9qTSWrIqq+ZtPzOA59ercIsj/UBFNs81Z9EMfPr
          9HFfNltO10RnIKvDc5sd7KTg+ybFyoouK6RkgejrstmTCdV58XearCJwLk5VRKE5
          6QEBwlz83xJJZ9djBKvQQ5q9p+MTx0gjEthzoYGpQcp9WNaSTPNwpFY3FqKue6tc
          ylpvSY61cYNTRQN99arSja0ni8fwRHVAMURqStyOm9/XMIqxo7IKc0NLh+HeuLbX
          kwIDAQAB
          -----END PUBLIC KEY-----
